config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'shared#index'

  resources :tweets do
    resources :comments
  end
  
  resources :users do
    member do 
      get :following, :followers
    end
  end

  resources :shared 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/follow.rb
class Follow <ActiveRecord::Base
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :comments

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :active_relationship, class_name: 'Follow', foreign_key: 'follower_id'
  has_many :passive_relationship, class_name: 'Follow', foreign_key: 'followed_id'
  has_many :block_relationship, class_name: 'Follow', foreign_key: 'follower_id'
  
  has_many :following, through: :active_relationship, source: :followed
  has_many :followers, through: :passive_relationship, source: :follower
  has_many :blocked_users, through: :block_relationship, source: :followed
  has_many :tweets

  def self.search(search)
      User.where('name LIKE ?', "%#{search}%")
  end

  def follow(user)
    unless is_blocked?(user)
      active_relationship.create(followed: user)
    else
      raise 'Sorry, the user that you try to follow blocked you'
    end
  end

  def unfollow(user)
    active_relationship.find_by(followed: user).destroy
  end

  def following?(user)
    following.include?(user)
  end

  def block(user)
    block_relationship.create(follower: user)
  end

  def unblock(user)
    block_relationship.find_by(followed: user).destroy
  end

  private

  def is_blocked?(user)
    blocked_users.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :nickname, :email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name,:nickname, :email, :password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def index
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.create(comment_params)
  end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController

  def index
    @tweet = Tweet.new

    following_ids = current_user.following.select(:id).map(&:id)
    @tweets = Tweet.where(user_id: following_ids).order(created_at: :desc).includes(:user)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = current_user.tweets.create(tweet_params)
    redirect_to root_url
  end

  private 

  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.search(params[:search])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterThingy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, class: 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, class: 'navbar-link'  %>
<% end %>

<%= yield %>

</body>
</html>

app/views/shared/_search.html.erb
<div class = 'navbar-text search_form'>
  <%= form_tag users_path, method: :get do %>
      <%= text_field_tag search: params[:search] %>
      <%= submit_tag 'Search', name: nil %>
  <% end %>
</div>

app/views/shared/_timeline.html.erb
<div class = 'timeline'>
  <table >
      <tr><h1 class = 'timeline_header'>Timeline </h1></tr>
    <tbody>    
      <% @tweets.each do |tweet| %>
        <tr>
          <td><strong><%= tweet.user.name %></strong></td>
        </tr>
        <tr class='border_bottom'>
          <td><%= tweet.body %></td>
        </tr>
      <% end %>   
    </tbody>
  </table>
</div>

app/views/shared/index.html.erb
<!DOCTYPE html>
<html>
  <body>

    <%= render 'search' %>
    <%= render '/tweets/create_tweet' %>
    <%= render 'timeline' %>
    
  </body>
</html>

app/views/tweets/_create_tweet.html.erb
<div class ='create_tweets'>
  <%= form_for(@tweet) do |f| %>
    <div class='field'>
      <%= f.text_area :body, placeholder: 'Enter a tweet...' %>
    </div>
    <%= f.submit 'Tweet', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/index.html.erb
<div class = 'search_form'>
  <%= form_tag users_path, method: :get do %>
      <%= text_field_tag search: params[:search] %>
      <%= submit_tag 'Search', name: nil %>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>